spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb_dev
    username: postgres
    password: my-dev-password  # Позже замени на {cipher}encrypted для шифрования
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka