#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE ${USER_DB_NAME:-user_db};
    CREATE DATABASE ${PROJECT_DB_NAME:-project_db};
    CREATE DATABASE ${TASK_DB_NAME:-task_db};
    CREATE DATABASE ${AUTH_DB_NAME:-auth_db};

    GRANT ALL PRIVILEGES ON DATABASE ${USER_DB_NAME:-user_db} TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE ${PROJECT_DB_NAME:-project_db} TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE ${TASK_DB_NAME:-task_db} TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE ${AUTH_DB_NAME:-auth_db} TO $POSTGRES_USER;
EOSQL